# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Production ]
    paths:
      - '**.cs'
  pull_request:
    branches: [ Production ]
    paths:
      - '**.cs'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Publish
      run: dotnet publish API/src/IO.Swagger/IO.Swagger.csproj
      
    - name: CopyConfigApp
      run: cp API/src/IO.Swagger/AppDeploy.yaml API/src/IO.Swagger/bin/Debug/netcoreapp2.0/publish/app.yaml

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: API/src/IO.Swagger/bin/Debug/netcoreapp2.0/publish/app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"